"""Add target_level to Subject

Revision ID: 9a5a8b225a8d
Revises: f8de8454d7c6
Create Date: 2026-05-04 18:24:17.269061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5a8b225a8d'
down_revision: Union[str, None] = 'f8de8454d7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('target_level', sa.String(length=50), nullable=False, server_default='intermediate'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'target_level')
    # ### end Alembic commands ###
