"""Add sort_order and metadata to topics

Revision ID: c246b9e931f7
Revises: 0c7c12af544c
Create Date: 2026-04-12 20:49:34.961045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c246b9e931f7'
down_revision: Union[str, None] = '0c7c12af544c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_concepts', sa.JSON(), nullable=False),
    sa.Column('formulas', sa.JSON(), nullable=False),
    sa.Column('study_tips', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('practice_problems', sa.JSON(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_cards_topic_id'), 'study_cards', ['topic_id'], unique=True)
    op.add_column('topics', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('topics', sa.Column('prerequisites', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('topics', sa.Column('key_concepts', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'key_concepts')
    op.drop_column('topics', 'prerequisites')
    op.drop_column('topics', 'sort_order')
    op.drop_index(op.f('ix_study_cards_topic_id'), table_name='study_cards')
    op.drop_table('study_cards')
    # ### end Alembic commands ###
